#!/usr/bin/env bash

if [ -z "$1" ]
then
    echo "Missing name argument"
    exit 1
fi
name="$1"

# Get machine folder from virtualbox system properties list
drives=$(VBoxManage list systemproperties \
    | grep -i 'Default machine folder' \
    | sed -e 's/^[^:]*:\s\+//;')

VBoxManage closemedium disk "$drives/$name/$name.vdi"
VBoxManage unregistervm "$name" --delete
rm -r "$drives/$name"

