#!/usr/bin/env bash

usage() {
    echo "Usage: $0 <vm-name> [iso-file]"
}

if [ -z "$1" ]
then
    echo "Missing name argument"
    usage
    exit 1
fi
name="$1"

iso=""

# Read iso filename if it is set
if [ -z "$2" ]
then
    iso="$HOME/iso/ubuntu-11.10-server-i386.iso"
else
    if [ ! -f "$2" -o ! -r "$2" ]
    then
        echo "$2 is not a readable regular file."
        exit 1
    fi
    iso="$2"
fi

# Get machine folder from virtualbox system properties list
drives=$(VBoxManage list systemproperties \
    | grep -i 'Default machine folder' \
    | sed -e 's/^[^:]*:\s\+//;')

VBoxManage createvm --name "$name" --register

hddpath="$drives/$name/$name.vdi"
VBoxManage createhd --size "3900" --filename "$hddpath"
VBoxManage storagectl "$name" --name "IDE Controller" --add ide
VBoxManage storageattach "$name" --storagectl "IDE Controller" \
                    --port 0 --device 1 --type hdd --medium "$hddpath"

VBoxManage modifyvm "$name" --memory "256"
VBoxManage modifyvm "$name" --nic1 "bridged"
VBoxManage modifyvm "$name" --bridgeadapter1 "eth0"

VBoxManage storageattach "$name" --storagectl "IDE Controller" \
                    --port 0 --device 0 --type dvddrive --medium "$iso"


